### ISSUE TITLE
OPD calculation does not use ng0 or ni0

### ISSUE THREAD

**Issue by kmdouglass** [hijizhou/MicroscPSF-ImageJ#1]
I discovered that the OPD calculation is inconsistent with the MATLAB version of this library. The problem, I think, is that some of the fields of `GibsonLanni.java` like ng0 and ni0 are not used in the calculation.

Below is a portion of the code that I ported to another Java library and which produces an output that agrees with the MATLAB and Python versions. You might be able to use this to check or correct this library's output.

Please note that you may need to change some of the variable names because I use a slightly different notation.

```java
// Oil thickness. I use only a single number for z (not an array),
// so you will need to change the line below.
ti = (this.ti0 + z);

double sqNA = this.NA * this.NA;
double rhoNA2;
for (int rhoi = 0; rhoi < this.numSamples; rhoi++) {
    rho = rhoi * deltaRho;
    rhoNA2 = rho * rho * sqNA;
                
    // OPD in the sample
    OPD = this.eZ * Math.sqrt(this.ns * this.ns - rhoNA2);
                
    // OPD in the immersion medium
    OPD += ti * Math.sqrt(this. ni * this.ni - rhoNA2) -
        this.ti0 * Math.sqrt(this.ni0 * this.ni0 - rhoNA2);

    // OPD in the coverslip
    OPD += this.tg * Math.sqrt(this.ng * this.ng - rhoNA2) -
        this.tg0 * Math.sqrt(this.ng0 * this.ng0 - rhoNA2);

    W = k0 * OPD;

    // You will need to change the second index back to that used in your notation
    Ffun[rhoi][0] = Math.cos(W);
    Ffun[rhoi][1] = Math.sin(W);
}
```

**Comment by hijizhou** [comment]
Thanks for pointing this mistake out. It has been fixed.
