### ISSUE TITLE
Born&Wolf PSF

### ISSUE THREAD

**Issue by WeisongZhao** [hijizhou/MicroscPSF-ImageJ#2]
Hi, it is a useful, and fast ij plugin! It seems that, even this plugin is based on Gibson-Lanni theory, I can use it to generate the Born&Wolf type PSF. But I have some trouble to do so, can you give me some advice about how to do this?
Many thanks!

**Comment by hijizhou** [comment]
Hi, thanks for your interests. Yes, it should be straightforward to extend to the Born-Wolf PSF model. You can change the phase function W accordingly, and then use rescaled Bessel functions to approximate this function. It may be necessary to tune a little bit some approximation parameters, for instance, the rescale parameter.

**Comment by WeisongZhao** [comment]
Thank you for your reply. BTW, If I want to generate the Born PSF with this Plugin UI directly, which parameter should be adjusted?

**Comment by hijizhou** [comment]
Hi Weisong, I would suggest changing the codes to obtain the Born-Wolf PSF model. I am not sure whether it is directly possible.
